baseURL = "https://orionuo.github.io/"
languageCode = "en-us"
title = "OrionUO: Ultima Online"
copyright = "© OrionUO Team"
author = "OrionUO Team"
theme = "landing-page"

enableRobotsTXT = true
canonifyUrls = "true"
enableEmoji = true

googleAnalytics = "UA-130616762-1"

paginate = 10
footnoteReturnLinkContents = "↩"

[permalinks]
	post = "/post/:year/:month/:day/:title/"
	page = "/:filename/"


[params]
    description = "The True Open Source Ultima Online Client"
    custom_css = ["css/local.css"]


[[params.social]]
    title = "discord"
    icon = "discord"
    url = "https://discord.gg/JbZsSmZ"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/OrionUO"
